Add first pass for Apache ActiveMQ Artemis support
php-enqueue/enqueue-dev pull request #1091
Opened 2020-09-23 13:29 UTC by atrauzzi

Hey @makasim! wave

I've managed to put together a first draft for supporting ActiveMQ Artemis using the Enqueue STOMP driver. I have this working locally and I've done my best to stick to your code style, giving in to the odd improvement.

The biggest change I've made is to plumb the notion of broker extensions a bit further into the hierarchy of objects. I noticed in quite a few places, RabbitMQ preferences are hard-coded because there wasn't any way to check which set of extensions are desired for the connection. I'll make further notes on the code in the PR to help you scan through things.

Let me know what you think and note any changes or improvements you're after. I have not added tests as I am hoping to get help from you on that if it's something you want done.

Closes: php-enqueue/enqueue-dev#1067

2020-09-23 13:54 UTC, makasim requested changes

2020-09-23 13:54 UTC, makasim commented on pkg/stomp/StompConnectionFactory.php
> +                fn () => $this->establishConnection(),
not sure it would work in php7.1

will it?

2020-09-23 13:54 UTC, makasim commented on pkg/stomp/StompConsumer.php
> +            throw new \Exception($e->getMessage() . "\n" . $e->getFrame()->getBody());
The library must throw only exceptions that implement [interop exception interface](https://github.com/queue-interop/queue-interop/blob/master/src/Exception/Exception.php).

2020-09-23 13:54 UTC, makasim commented on pkg/stomp/StompConsumer.php
> +            if ($this->queue->getExtensionType() === ExtensionType::ARTEMIS) {
could be `} else if {`

2020-09-23 13:54 UTC, makasim commented on pkg/stomp/StompConsumer.php
> +                $subscriptionName = "{$this->subscriptionId}-{$this->queue->getStompName()}";
```php
$subscriptionName = $this->subscriptionId."-".$this->queue->getStompName();
```

2020-09-23 13:54 UTC, makasim commented on pkg/stomp/StompConsumer.php
> +        [$headers, $properties] = StompHeadersEncoder::decode($frame->getHeaders());
does it work in php7.1 ?

2020-09-23 13:54 UTC, makasim commented
@atrauzzi it looks good to me. There are only some minor comments

2020-09-23 14:02 UTC, atrauzzi commented
Wonderful, I'll get on making the fixes.

2020-09-23 17:23 UTC, makasim commented
There are some CS issues and failing tests. Could you please fix them (only stuff related to your PR)?

2020-09-23 17:23 UTC, makasim commented
https://travis-ci.org/github/php-enqueue/enqueue-dev/builds/729639649

2020-09-23 19:19 UTC, atrauzzi commented
I'll check into it!

2020-09-24 18:22 UTC, atrauzzi commented
@makasim - Alright, I think I've got it down now?

2020-09-24 18:52 UTC, makasim approved these changes

2020-09-24 18:52 UTC, merged

2020-09-24 18:52 UTC, makasim commented
Thank you!

2020-09-24 18:58 UTC, atrauzzi commented
My pleasure, thank **you** for this library! :smile:

2020-09-24 19:02 UTC, makasim commented
@atrauzzi https://github.com/php-enqueue/stomp/releases/tag/0.10.4